### ISSUE TITLE
API Usage Demo - Outdated URL

### ISSUE THREAD

**Issue by bccummings** [uwmadison-chm/bioread#23]
Hello!

I noticed that the hyperlink to the API usage demo was broken in the README - it seems it didn't update when the repo was moved to the uwmadison-chm group. 

It currently points to:

http://njvack.github.io/bioread/bioread_quick_demo.html

But looks like it should instead go to:

http://uwmadison-chm.github.io/bioread/bioread_quick_demo.html

Thank you so much for your excellent work on these tools - they have been a lifesaver for me on countless occasions!

Brandon

**Comment by dgfitch** [comment]
Thanks for catching that Brandon! I fixed it. We all agree, Nate is the coolest.

**Comment by njvack** [comment]
Holy crap, it's awesome to have someone else looking at this stuff as well as me, @dgfitch. Thank you!

And @bccummings, thank you so much for both reporting this issue and your kind words. It means a lot!
