### ISSUE TITLE
Switch to pyproject.toml

### ISSUE THREAD

**Issue by njvack** [uwmadison-chm/bioread#33]
The main operational question is: What do we do with version numbers? It'd be real nice to generate them based off of git tags, maybe we can use a hook to do it?

For now, I'm just gonna put the version number in both places, we can figure something more clever out later.

**Comment by njvack** [comment]
Okaaaaaaaaaaaaaay. It turns out that maybe this isn't somethingy you "switch to." I don't think this gains anything and it costs something, so I'm not gonna bother. If someone who understands the cluster**** world of python packaging knows how to set this all up properly, I'd welcome a packaging PR. For now, I'm gonna close this and tag for 2.0

**Comment by dgfitch** [comment]
It seems like this is all maybe a tiny bit of a moving target anyway? Thanks for digging into it...
