### ISSUE TITLE
Please share wheel file on pypi

### ISSUE THREAD

**Issue by shMeske** [uwmadison-chm/bioread#41]
Hi

I want to use your package for website in order to analyze different biological signals so that users who can't program can analyze their data. For that I use the ecosystem [Panel](https://panel.holoviz.org/). This ecosystem uses Pyodide or Pyscript so that the data app can run in the browser.

The issue is that pingouin does not release wheel files on pypi. As far as I can see it should be possible to release.

Please consider doing so. Thanks.

**Comment by njvack** [comment]
I should(!) be able to do this, I think; honestly, I've been copying a bunch of python installs around lately and source distributions suck.

But to be 100% clear, this is not the pingoiun package

**Comment by shMeske** [comment]
That would be awesome. 👍 

Oh I'm sorry, I had to request the same for pingouin and I didn't correct the text.

**Comment by njvack** [comment]
oh god I have to package another release, how do I do this, I should know how to do this but it has been so long and the recommendations for building a python package change every three weeks

**Comment by njvack** [comment]
okay I think I have done it, give it a try

https://pypi.org/project/bioread/3.0.0/#files

feelin' like a super professional coder-man here
